In [1]:
import pandas as pd

In [2]:
data = pd.read_excel(r'FI_LATEST_RAWDATA.xlsx')

In [3]:
data.head()

,start,end,Search Geo Coordinates,_Search Geo Coordinates_latitude,_Search Geo Coordinates_longitude,_Search Geo Coordinates_altitude,_Search Geo Coordinates_precision,"Dear respondent, My name is ………………………I am from CFI/UNESWA I am from CFI/INISWA which are entities that are jointly undertaking a financial inclusion investigation. I am happy to say that you are one of the selected respondents, I am here today to ask you a few questions on where you access financial services, how you manage and use financial services and products, for Government to draw policy recommendations on how financial services and products can be better offered closer to where you live or work.",2. Region,3. Nationality,...,Saving,Credit,Remittances,Mobile Money,Transactions,Financially_Included,Depth of FI,Financially_included,Depth_of_FI,Weights
0,2022-04-26 09:21:34.515,2022-04-26 09:39:32.067,-27.2578881 31.4356487 872.0999755859375 5.6,-27.257888,31.435649,872.099976,5.60,OK,Shiselweni,Liswati,...,2.0,1.0,NaN,2.0,NaN,1.0,3.0,Banked,Three financial products,NaN
1,2022-04-26 09:37:55.129,2022-04-26 09:53:07.865,-27.1961735 31.419029 830.7999877929688 8.75,-27.196174,31.419029,830.799988,8.75,OK,Shiselweni,Liswati,...,1.0,3.0,2.0,2.0,1.0,1.0,5.0,Banked,Five financial products,NaN
2,2022-04-26 09:53:14.626,2022-04-26 10:08:45.503,-27.1960567 31.4190278 800.5900268554688 11.5,-27.196057,31.419028,800.590027,11.50,OK,Shiselweni,Liswati,...,NaN,3.0,2.0,2.0,1.0,1.0,4.0,Banked,Four financial products,NaN
3,2022-04-26 09:27:58.696,2022-04-26 10:10:58.105,-27.2948715 31.5443429 486.572226077288 4.9,-27.294871,31.544343,486.572226,4.90,OK,Shiselweni,Liswati,...,1.0,NaN,1.0,2.0,1.0,1.0,4.0,Banked,Four financial products,NaN
4,2022-04-26 09:55:42.120,2022-04-26 10:09:38.818,-27.2949856 31.5443693 487.93094312222695 4.88,-27.294986,31.544369,487.930943,4.88,OK,Shiselweni,Swazis,...,1.0,NaN,1.0,2.0,NaN,1.0,4.0,Banked,Four financial products,NaN

<bound method DataFrame.info of                       start                     end  \
0   2022-04-26 09:21:34.515 2022-04-26 09:39:32.067
1   2022-04-26 09:37:55.129 2022-04-26 09:53:07.865
2   2022-04-26 09:53:14.626 2022-04-26 10:08:45.503
3   2022-04-26 09:27:58.696 2022-04-26 10:10:58.105
4   2022-04-26 09:55:42.120 2022-04-26 10:09:38.818
..                      ...                     ...
398                     NaT                     NaT
399                     NaT                     NaT
400                     NaT                     NaT
401                     NaT                     NaT
402                     NaT                     NaT

                                Search Geo Coordinates  \
0         -27.2578881 31.4356487 872.0999755859375 5.6
1         -27.1961735 31.419029 830.7999877929688 8.75
2        -27.1960567 31.4190278 800.5900268554688 11.5
3          -27.2948715 31.5443429 486.572226077288 4.9
4       -27.2949856 31.5443693 487.93094312222695 4.88
..                                                 ...
398                  2. Receive and send remmittances
399             3. People able to mitigate (insurance)
400                       4. Be able to access credit
401                                  5. Make payments
402  6. Optional, Receiving a Govt Grant, social gr...

     _Search Geo Coordinates_latitude  _Search Geo Coordinates_longitude  \
0                          -27.257888                          31.435649
1                          -27.196174                          31.419029
2                          -27.196057                          31.419028
3                          -27.294871                          31.544343
4                          -27.294986                          31.544369
..                                ...                                ...
398                               NaN                                NaN
399                               NaN                                NaN
400                               NaN                                NaN
401                               NaN                                NaN
402                               NaN                                NaN

     _Search Geo Coordinates_altitude  _Search Geo Coordinates_precision  \
0                          872.099976                               5.60
1                          830.799988                               8.75
2                          800.590027                              11.50
3                          486.572226                               4.90
4                          487.930943                               4.88
..                                ...                                ...
398                               NaN                                NaN
399                               NaN                                NaN
400                               NaN                                NaN
401                               NaN                                NaN
402                               NaN                                NaN

    Dear respondent, My name is ………………………I am from CFI/UNESWA I am from CFI/INISWA which are entities that are jointly undertaking a financial inclusion investigation. I am happy to say that you are one of the selected respondents, I am here today to ask you a few questions on where you access financial services, how you manage and use financial services and products, for Government to draw policy recommendations on how financial services and products can be better offered closer to where you live or work.  \
0                                                   OK
1                                                   OK
2                                                   OK
3                                                   OK
4                                                   OK
..                                                 ...
398                                                NaN
399                                                NaN
400                                                NaN
401                                                NaN
402                                                NaN

      2. Region 3. Nationality  ... Saving  Credit  Remittances  \
0    Shiselweni        Liswati  ...     2.0     1.0         NaN
1    Shiselweni        Liswati  ...     1.0     3.0         2.0
2    Shiselweni        Liswati  ...     NaN     3.0         2.0
3    Shiselweni        Liswati  ...     1.0     NaN         1.0
4    Shiselweni         Swazis  ...     1.0     NaN         1.0
..          ...            ...  ...     ...     ...         ...
398         NaN            NaN  ...     NaN     NaN         NaN
399         NaN            NaN  ...     NaN     NaN         NaN
400         NaN            NaN  ...     NaN     NaN         NaN
401         NaN            NaN  ...     NaN     NaN         NaN
402         NaN            NaN  ...     NaN     NaN         NaN

     Mobile Money  Transactions Financially_Included Depth of FI  \
0              2.0          NaN                  1.0         3.0
1              2.0          1.0                  1.0         5.0
2              2.0          1.0                  1.0         4.0
3              2.0          1.0                  1.0         4.0
4              2.0          NaN                  1.0         4.0
..             ...          ...                  ...         ...
398            NaN          NaN                  NaN         NaN
399            NaN          NaN                  NaN         NaN
400            NaN          NaN                  NaN         NaN
401            NaN          NaN                  NaN         NaN
402            NaN          NaN                  NaN         NaN

    Financially_included               Depth_of_FI Weights
0                 Banked  Three financial products     NaN
1                 Banked  Five financial products      NaN
2                 Banked   Four financial products     NaN
3                 Banked   Four financial products     NaN
4                 Banked   Four financial products     NaN
..                   ...                       ...     ...
398                  NaN                       NaN     NaN
399                  NaN                       NaN     NaN
400                  NaN                       NaN     NaN
401                  NaN                       NaN     NaN
402                  NaN                       NaN     NaN

[403 rows x 340 columns]>